=pod

=encoding UTF-8

=head1 ABOUT

Sample book catalogue service written using L<Dancer2>, L<DBIx::Class>, and L<Plack/PSGI|https://plackperl.org/>

=head1 VERSION

v0.2.0

=head1 SYNOPSIS

    # Recreate the db, load data and run:
    .\app.pl recreate
    .\app.pl load
    .\app.pl
    # Or all at once
    perl .\app.pl recreate --yes load run
    # Or, with Dancer
    perl .\app.pl recreate --yes load dance

=head1 DESCRIPTION

=head3 Building with Docker

Using Docker to build and customize image containing this application:

    docker image build -t perl_dancer2_sample_service .

=head1 USED LIBRARIES AND DEPENDENCIES

=begin html

<table>

<tr>
<th>What is used</th>
<th>Version</th>
</tr>

<tr>
<td>Perl</td>
<td>5.30</td>
</tr>

<tr>
<td>Dancer2</td>
<td>0.300005</td>
</tr>

<tr>
<td>Dancer2::Plugin::DBIC</td>
<td>0.0100</td>
</tr>

<tr>
<td>DBIx::Class</td>
<td>0.082841</td>
</tr>

<tr>
<td>Dancer2::Template::Xslate</td>
<td>v0.1.2</td>
</tr>

<tr>
<td>Text::Xslate</td>
<td>v3.5.7</td>
</tr>

<tr>
<td>Plack</td>
<td>1.0047</td>
</tr>

</table>

=end html

=head1 SEE ALSO

=over 4

=item * Dancer2 L<Dancer2>

=item * DBIx::Class L<DBIx::Class>

=item * Plack/PSGI L<https://plackperl.org/>

=item * Mojolicious L<Mojolicious>

=item * Text::Xslate L<Text::Xslate>

=item * Gazelle L<Gazelle>

=back

=head1 AUTHORS

Vasyl, basilwashere[at]gmail.com, year-year

=head1 CONTRIBUTING

Feel free to ❤🐪

=head1 COPYRIGHT AND LICENSE

This project is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
